[2023-11-05T16:15:10.457+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_People_Places.load_places manual__2023-11-05T16:15:09.200912+00:00 [queued]>
[2023-11-05T16:15:10.473+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_People_Places.load_places manual__2023-11-05T16:15:09.200912+00:00 [queued]>
[2023-11-05T16:15:10.474+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-11-05T16:15:10.476+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-11-05T16:15:10.477+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-11-05T16:15:10.497+0000] {taskinstance.py:1309} INFO - Executing <Task(DockerOperator): load_places> on 2023-11-05 16:15:09.200912+00:00
[2023-11-05T16:15:10.502+0000] {standard_task_runner.py:55} INFO - Started process 332 to run task
[2023-11-05T16:15:10.506+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ETL_People_Places', 'load_places', 'manual__2023-11-05T16:15:09.200912+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/ETL_people_places_dag.py', '--cfg-path', '/tmp/tmp4wag66_p']
[2023-11-05T16:15:10.511+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask load_places
[2023-11-05T16:15:10.606+0000] {task_command.py:389} INFO - Running <TaskInstance: ETL_People_Places.load_places manual__2023-11-05T16:15:09.200912+00:00 [running]> on host 6e77a7a050e2
[2023-11-05T16:15:10.710+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ETL_People_Places
AIRFLOW_CTX_TASK_ID=load_places
AIRFLOW_CTX_EXECUTION_DATE=2023-11-05T16:15:09.200912+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-11-05T16:15:09.200912+00:00
[2023-11-05T16:15:10.760+0000] {docker.py:306} INFO - Starting docker container from image load_places:latest
[2023-11-05T16:15:14.549+0000] {taskinstance.py:1332} INFO - Marking task as SUCCESS. dag_id=ETL_People_Places, task_id=load_places, execution_date=20231105T161509, start_date=20231105T161510, end_date=20231105T161514
[2023-11-05T16:15:14.598+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-11-05T16:15:14.637+0000] {taskinstance.py:2596} INFO - 1 downstream tasks scheduled from follow-on schedule check
